name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: 3331680c-3cca-4ffc-90d7-e1709c3303f0
        MESSAGE: "Hey Sam Baird, there's a new build"
